# action.yml
name: 'Pytest-coverage-commenter'
description: 'Github action to add coverage report as comment'
inputs:
  service-name:
    description: 'Name of service'
    required: true
    default: ''
  service-directory:
    description: 'Path of folder of service'
    required: false
    default: './'
  github-token:
    description: 'Github token for authentication'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service-name }}
    - ${{ inputs.service-directory }}
    - ${{ inputs.github-token }}