# action.yml
name: 'Pytest-coverage-commenter'
description: 'Github action to add coverage report as comment'
inputs:
  service-name:
    description: 'Name of service'
    required: true
    default: ''
  coverage-report:
    description: 'Output of coverage report run'
    required: true
  github-token:
    description: 'Github token for authentication'
    required: true
  github-repo:
    description: 'Owner/name of github repo'
    required: false
    default: ${{ github.repository }}
  github-issue:
    description: 'Pull request issue number'
    required: false
    default: ${{ github.event.pull_request.number }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service-name }}
    - ${{ inputs.coverage-report }}
    - ${{ inputs.github-token }}
    - ${{ inputs.github-repo }}
    - ${{ inputs.github-issue }}