name: Run Tests

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Build Test Containers
      run: docker-compose build coverage_commenter_test
    
    - name: Test with pytest
      run: |
        docker-compose run coverage_commenter_test pipenv run pytest
    